/**
 * SQL Attribution Tests
 *
 * Tests the trackSQL feature that captures the raw SQL generated by Malloy
 * for each query and makes it available on each cell via CellValue.sql
 * and CellValue.cellSQL.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { parse } from '../dist/parser/index.js';
import {
  buildTableSpec,
  generateQueryPlan,
  generateMalloyQueries,
  buildGridSpec,
} from '../dist/compiler/index.js';
import { renderGridToHTML } from '../dist/renderer/index.js';
import {
  createLocalConnection,
  getDefaultSource,
  executeMalloy,
  setPendingConnection,
} from '../dist/executor/index.js';
import { TPL } from '../dist/index.js';
import type { GridSpec, CellValue, DimensionValues } from '../dist/compiler/table-spec.js';

let DEFAULT_SOURCE: string;

beforeAll(async () => {
  await createLocalConnection();
  DEFAULT_SOURCE = getDefaultSource();
});

/**
 * Helper: run the full pipeline with SQL tracking enabled.
 */
async function runWithSQL(tpl: string): Promise<{
  html: string;
  grid: GridSpec;
  sqlQueries: Map<string, string>;
  malloyQueries: ReturnType<typeof generateMalloyQueries>;
}> {
  const ast = parse(tpl);
  const spec = buildTableSpec(ast);
  const plan = generateQueryPlan(spec);
  const queries = generateMalloyQueries(plan, 'names', { where: spec.where });

  const queryResults = new Map<string, any[]>();
  const sqlQueries = new Map<string, string>();

  for (const queryInfo of queries) {
    const fullMalloy = `${DEFAULT_SOURCE}\n${queryInfo.malloy}`;
    const result = await executeMalloy(fullMalloy, { captureSQL: true });
    queryResults.set(queryInfo.id, result.data);
    if (result.sql) {
      sqlQueries.set(queryInfo.id, result.sql);
    }
  }

  const grid = buildGridSpec(spec, plan, queryResults, {
    malloyQueries: queries,
    sqlQueries,
  });
  const html = renderGridToHTML(grid);

  return { html, grid, sqlQueries, malloyQueries: queries };
}

/**
 * Helper: run the full pipeline WITHOUT SQL tracking (default behavior).
 */
async function runWithoutSQL(tpl: string): Promise<{
  html: string;
  grid: GridSpec;
}> {
  const ast = parse(tpl);
  const spec = buildTableSpec(ast);
  const plan = generateQueryPlan(spec);
  const queries = generateMalloyQueries(plan, 'names', { where: spec.where });

  const queryResults = new Map<string, any[]>();
  for (const queryInfo of queries) {
    const fullMalloy = `${DEFAULT_SOURCE}\n${queryInfo.malloy}`;
    const data = await executeMalloy(fullMalloy);
    queryResults.set(queryInfo.id, data);
  }

  const grid = buildGridSpec(spec, plan, queryResults, {
    malloyQueries: queries,
  });
  const html = renderGridToHTML(grid);

  return { html, grid };
}

describe('SQL Attribution (trackSQL)', () => {
  describe('SQL capture from Malloy runtime', () => {
    it('captures SQL for a simple query', async () => {
      const result = await runWithSQL('TABLE ROWS state[-5] * births.sum;');

      // Should have exactly one query
      expect(result.sqlQueries.size).toBe(1);

      // The SQL should be a real SQL string
      const sql = result.sqlQueries.get('q0')!;
      expect(sql).toBeDefined();
      expect(sql).toContain('SELECT');
      // Should reference births in some form (as aggregation)
      expect(sql.toLowerCase()).toMatch(/sum|births/);
    });

    it('captures SQL for a pivot table with rows and cols', async () => {
      const result = await runWithSQL('TABLE ROWS state[-3] * births.sum COLS year[-3];');

      expect(result.sqlQueries.size).toBeGreaterThanOrEqual(1);

      const sql = result.sqlQueries.get('q0')!;
      expect(sql).toBeDefined();
      expect(sql).toContain('SELECT');
    });
  });

  describe('CellValue SQL attribution', () => {
    it('provides sql and cellSQL on each cell when tracking is enabled', async () => {
      const result = await runWithSQL('TABLE ROWS state[-3] * births.sum;');

      // Get a cell
      const rowValues: DimensionValues = new Map();
      // We don't know the exact state, so let's get the first row header value
      const firstRow = result.grid.rowHeaders[0];
      if (firstRow?.dimension) {
        rowValues.set(firstRow.dimension, firstRow.value);
      }
      const colValues: DimensionValues = new Map();
      const cell = result.grid.getCell(rowValues, colValues);

      // Cell should have SQL attribution
      expect(cell.sql).toBeDefined();
      expect(cell.sql).toContain('SELECT');

      // Cell-specific SQL should wrap the base SQL with a WHERE clause
      expect(cell.cellSQL).toBeDefined();
      expect(cell.cellSQL).toContain('_tpl_base');
      expect(cell.cellSQL).toContain('WHERE');
    });

    it('does NOT provide sql when tracking is disabled', async () => {
      const result = await runWithoutSQL('TABLE ROWS state[-3] * births.sum;');

      const rowValues: DimensionValues = new Map();
      const firstRow = result.grid.rowHeaders[0];
      if (firstRow?.dimension) {
        rowValues.set(firstRow.dimension, firstRow.value);
      }
      const colValues: DimensionValues = new Map();
      const cell = result.grid.getCell(rowValues, colValues);

      // Cell should NOT have SQL when tracking is off
      expect(cell.sql).toBeUndefined();
      expect(cell.cellSQL).toBeUndefined();
    });

    it('includes dimension values in cellSQL WHERE clause', async () => {
      const result = await runWithSQL('TABLE ROWS state[-3] * births.sum COLS year[-2];');

      // Find a cell with both row and col dimension values
      const firstRow = result.grid.rowHeaders[0];
      const firstCol = result.grid.colHeaders[0];

      if (firstRow?.dimension && firstCol?.dimension) {
        const rowValues: DimensionValues = new Map([[firstRow.dimension, firstRow.value]]);
        const colValues: DimensionValues = new Map([[firstCol.dimension, firstCol.value]]);
        const cell = result.grid.getCell(rowValues, colValues);

        expect(cell.cellSQL).toBeDefined();
        // The cellSQL should filter for the specific dimension values
        expect(cell.cellSQL).toContain(String(firstRow.value));
        expect(cell.cellSQL).toContain(String(firstCol.value));
      }
    });

    it('all cells from the same query share the same base SQL', async () => {
      const result = await runWithSQL('TABLE ROWS state[-3] * births.sum;');

      // Get cells for different rows - they should all have the same base SQL
      const sqlValues = new Set<string>();
      for (const header of result.grid.rowHeaders) {
        if (header.dimension) {
          const rowValues: DimensionValues = new Map([[header.dimension, header.value]]);
          const cell = result.grid.getCell(rowValues, new Map());
          if (cell.sql) {
            sqlValues.add(cell.sql);
          }
        }
      }

      // All cells should share the same SQL (one query for this simple case)
      expect(sqlValues.size).toBe(1);
    });
  });

  describe('HTML data attributes', () => {
    it('emits data-sql attribute on cells when tracking is enabled', async () => {
      const result = await runWithSQL('TABLE ROWS state[-3] * births.sum;');

      // HTML should contain data-sql attributes
      expect(result.html).toContain('data-sql=');
      // The SQL should contain SELECT
      expect(result.html).toMatch(/data-sql="[^"]*SELECT/);
    });

    it('emits data-cell-sql attribute on cells when tracking is enabled', async () => {
      const result = await runWithSQL('TABLE ROWS state[-3] * births.sum;');

      // HTML should contain data-cell-sql attributes
      expect(result.html).toContain('data-cell-sql=');
      expect(result.html).toMatch(/data-cell-sql="[^"]*WHERE/);
    });

    it('does NOT emit data-sql when tracking is disabled', async () => {
      const result = await runWithoutSQL('TABLE ROWS state[-3] * births.sum;');

      expect(result.html).not.toContain('data-sql=');
      expect(result.html).not.toContain('data-cell-sql=');
    });
  });

  describe('Multi-query scenarios', () => {
    it('tracks SQL for concatenated axes (multiple queries)', async () => {
      const result = await runWithSQL(
        'TABLE ROWS (state[-3] | gender) * births.sum;'
      );

      // Should have at least one query (may be deduplicated)
      expect(result.sqlQueries.size).toBeGreaterThanOrEqual(1);

      // All captured SQL should be valid SELECT statements
      for (const sql of result.sqlQueries.values()) {
        expect(sql).toContain('SELECT');
      }

      // Find a cell that has data — look for a gender dimension value
      // since that's a simple dimension without limits
      const genderCell = result.grid.getCell(
        new Map([['gender', 'M']]),
        new Map()
      );
      expect(genderCell.raw).not.toBeNull();
      expect(genderCell.sql).toBeDefined();
    });
  });

  describe('Edge cases', () => {
    it('handles percentage/ACROSS queries', async () => {
      const result = await runWithSQL(
        'TABLE ROWS state[-3] * (births.sum ACROSS) COLS gender;'
      );

      expect(result.sqlQueries.size).toBeGreaterThanOrEqual(1);
      const sql = [...result.sqlQueries.values()][0];
      expect(sql).toContain('SELECT');
    });

    it('handles tables with ALL (totals)', async () => {
      const result = await runWithSQL(
        'TABLE ROWS (state[-3] | ALL) * births.sum;'
      );

      expect(result.sqlQueries.size).toBeGreaterThanOrEqual(1);

      // The total row cell should also have SQL attribution
      // Find the ALL row
      const totalRow = result.grid.rowHeaders.find(h => h.type === 'total');
      if (totalRow) {
        const cell = result.grid.getCell(new Map(), new Map());
        expect(cell.sql).toBeDefined();
      }
    });
  });

  describe('High-level TPL API with trackSQL', () => {
    it('tracks SQL via TPL class with trackSQL option', async () => {
      setPendingConnection({ type: 'duckdb' });
      const tpl = new TPL({ trackSQL: true });

      const result = await tpl.execute(
        'TABLE ROWS state[-3] * births.sum COLS year[-2];',
        { model: DEFAULT_SOURCE, sourceName: 'names' }
      );

      // ExecuteResult should include sqlQueries
      expect(result.sqlQueries).toBeDefined();
      expect(result.sqlQueries!.size).toBeGreaterThanOrEqual(1);

      // SQL should be a real SELECT statement
      const sql = [...result.sqlQueries!.values()][0];
      expect(sql).toContain('SELECT');

      // HTML should contain data-sql attributes
      expect(result.html).toContain('data-sql=');

      // GridSpec cells should have SQL
      const firstRow = result.grid.rowHeaders[0];
      const firstCol = result.grid.colHeaders[0];
      if (firstRow?.dimension && firstCol?.dimension) {
        const cell = result.grid.getCell(
          new Map([[firstRow.dimension, firstRow.value]]),
          new Map([[firstCol.dimension, firstCol.value]])
        );
        expect(cell.sql).toBeDefined();
        expect(cell.cellSQL).toBeDefined();
        expect(cell.cellSQL).toContain('WHERE');
      }
    });

    it('does NOT track SQL when trackSQL is not set', async () => {
      setPendingConnection({ type: 'duckdb' });
      const tpl = new TPL();

      const result = await tpl.execute(
        'TABLE ROWS state[-3] * births.sum;',
        { model: DEFAULT_SOURCE, sourceName: 'names' }
      );

      // ExecuteResult should NOT include sqlQueries
      expect(result.sqlQueries).toBeUndefined();

      // HTML should not contain data-sql
      expect(result.html).not.toContain('data-sql=');
    });
  });
});
